
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// To change the Firebase project, run the "Change Firebase Project" command from the command-ax
// You can also right-click on the docs/studio-config.json file and select the "Change Firebase Project" command.
export const firebaseConfig = {
  "projectId": "studio-8339212723-be4ad",
  "appId": "1:416650495331:web:fcdc55bf754a2d1ef57f56",
  "apiKey": "AIzaSyAcum56T5FOD5zEYB9hMkvC3JzaboKGM88",
  "authDomain": "studio-8339212723-be4ad.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "416650495331",
  "storageBucket": "studio-8339212723-be4ad.appspot.com"
};
