# Generated by Django 4.2.7 on 2025-09-25 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_inventorybatch_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproduct',
            options={'ordering': ['supplier__name', 'product__name']},
        ),
        migrations.RemoveField(
            model_name='inventorybatch',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventorybatch',
            name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='inventorybatch',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_registration',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='minimum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='supplier_sku',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='last_supplied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='min_order_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Which supplier provided this batch (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this batch', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, help_text='Lead time in days', null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='inventory.product'),
        ),
    ]
