# Generated by Django 4.2.7 on 2025-10-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productdailysales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_status',
            field=models.CharField(choices=[('OK', 'OK'), ('APPROACHING', 'Approaching Minimum'), ('LOW', 'Below Minimum')], default='OK', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_warning_buffer_pct',
            field=models.PositiveIntegerField(default=20, help_text='Percent above minimum to start warning'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPROACHING', 'Approaching Minimum'), ('LOW', 'Below Minimum')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('current_stock_at_trigger', models.PositiveIntegerField()),
                ('minimum_stock_level', models.PositiveIntegerField()),
                ('message', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active'], name='inventory_s_active_042f0c_idx'), models.Index(fields=['status'], name='inventory_s_status_95e312_idx')],
            },
        ),
    ]
