# Generated by Django 4.2.7 on 2025-10-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_reorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock_level', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_snapshots', to='inventory.product')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', 'date'], name='inventory_p_product_9e501f_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
